name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    if: "startsWith(github.event.head_commit.message, '[DEV-RELEASE]')"
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t comics-fe .
        docker tag comics-fe nryan1987/comics-fe:dev-latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push nryan1987/comics-fe:dev-latest
