name: Version Increment

on:
  push:
    branches: [ "dev" ]

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[DEV-RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name 'AboutBits Tech'
      - run: git config --global user.email 'tech@aboutbits.it'
      - run: npm version minor -m "[DEV-RELEASE] %s"
      - run: git push
